import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex items-center">
          <Image src="/truskawka.jpg" alt="My favorite fruit" width={100} height={100} />
          <h1 className="mb-4 text-4xl font-bold tracking-tight">
            Next.js CRUD App
          </h1>
        </div>
        <hr />
        <p>&nbsp;</p>
        
        {children}

        <p>Created by Łukasz Bialik</p>
      </body>
    </html>
  );
}